---
- name: ppa dependencies
  sudo: yes
  apt: name={{item}} update_cache=yes cache_valid_time=300
  with_items:
    - python-software-properties

- name: brightbox ruby repo
  sudo: yes
  apt_repository: repo=ppa:brightbox/ruby-ng update_cache=yes

- name: install ruby packages
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
    - ruby-switch
    - "{{brightbox_ruby_version}}"
    - "{{brightbox_ruby_version}}-dev"

- name: switch to {{brightbox_ruby_version}}
  sudo: yes
  shell: ruby-switch --set {{brightbox_ruby_version}}

- name: install default gems
  sudo: yes
  command: gem install {{item}} --no-document
  with_items: brightbox_ruby_default_gems
